# Generated by Django 4.1.1 on 2022-10-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='https://i.imgur.com/WxNkK7J.png', null=True, upload_to=''),
        ),
    ]
