# Generated by Django 4.1.1 on 2022-11-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='short_des',
            field=models.TextField(null=True),
        ),
    ]
