# Generated by Django 4.1.1 on 2022-11-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
