# Generated by Django 4.1.1 on 2022-11-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_problem_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='icon',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
