# Generated by Django 4.1.3 on 2022-12-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("home", "0014_code_language")]

    operations = [migrations.DeleteModel(name="Code")]
