# Generated by Django 4.1.3 on 2022-12-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0015_delete_code")]

    operations = [
        migrations.AddField(
            model_name="problem", name="testcase", field=models.TextField(blank=True)
        )
    ]
