# Generated by Django 4.1.3 on 2022-12-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0017_problem_result")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="solved_chall",
            field=models.ManyToManyField(to="home.problem"),
        )
    ]
