# Generated by Django 4.1.3 on 2022-12-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0019_remove_user_solved_chall")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="solved_chall",
            field=models.ManyToManyField(blank=True, to="home.problem"),
        )
    ]
