# Generated by Django 4.1.3 on 2022-12-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("home", "0020_user_solved_chall")]

    operations = [migrations.RemoveField(model_name="user", name="solved_chall")]
